"""
Export verified COLLIDER decision memory into IBM Bob workspace rules.

The output is intentionally simple Markdown because Bob workspace rules are
plain text files under .bob/rules/. This turns an approved semantic decision
into context that future Bob agents automatically receive.

Exporting a rule does not prove that a future agent obeyed it. That requires a
separate fresh-agent replay.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def render_decision_rules(memory: dict[str, Any], source_path: str) -> str:
    if memory.get("schema") != "collider.decision-memory/v1":
        raise ValueError("unsupported or missing COLLIDER decision-memory schema")

    decisions = memory.get("decisions")
    if not isinstance(decisions, list) or not decisions:
        raise ValueError("decision memory contains no decisions")

    lines = [
        "# COLLIDER canonical decision memory",
        "",
        "> Generated from verified COLLIDER decision memory.",
        "> Do not edit this file by hand; re-export after an approved decision.",
        "",
        "Bob must treat the decisions below as project canon when working on the",
        "listed concepts. If a requested change conflicts with canon, do not",
        "silently overwrite the decision. Run the COLLIDER semantic guard and",
        "surface MERGE_BLOCKED or request a new human decision when appropriate.",
        "",
        f"Source memory: `{source_path}`",
        "",
    ]

    for decision in decisions:
        required = ("decision_id", "concept", "canonical_value", "decision_state")
        missing = [field for field in required if field not in decision]
        if missing:
            raise ValueError(
                f"decision missing required fields: {', '.join(missing)}"
            )

        if decision["decision_state"] != "CANONICAL":
            continue

        lines.extend(
            [
                f"## {decision['concept']}",
                "",
                f"- Canonical value: `{decision['canonical_value']}`",
                f"- Decision ID: `{decision['decision_id']}`",
                f"- Decision source: `{decision.get('decision_source', 'UNKNOWN')}`",
                f"- Human decision source: `{decision.get('human_decision_source', 'UNKNOWN')}`",
                f"- Prior classification: `{decision.get('prior_classification', 'UNKNOWN')}`",
                f"- Evidence state: `{decision.get('evidence_state', 'UNKNOWN')}`",
                "",
                "### Bob enforcement",
                "",
                (
                    f"When implementing or reviewing `{decision['concept']}`, use "
                    f"`{decision['canonical_value']}` unless a new authorized human "
                    "decision explicitly supersedes this canon."
                ),
                "",
            ]
        )

    if not any(line.startswith("## ") for line in lines):
        raise ValueError("decision memory contains no CANONICAL decisions")

    lines.extend(
        [
            "## Truth boundary",
            "",
            "- This rule records an approved decision; it does not convert unrelated",
            "  inferences into facts.",
            "- New concepts not covered here may still be UNKNOWN.",
            "- A future Bob agent's compliance is not proven until executed and checked.",
            "",
        ]
    )

    return "\n".join(lines)


def export_decision_rules(memory_path: str | Path, output_path: str | Path) -> Path:
    source = Path(memory_path)
    memory = json.loads(source.read_text())
    rendered = render_decision_rules(memory, str(source))

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered)
    return output


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Export COLLIDER decision memory into IBM Bob workspace rules"
    )
    parser.add_argument("--memory", required=True)
    parser.add_argument(
        "--output",
        default=".bob/rules/collider-decision-memory.md",
    )
    args = parser.parse_args()

    try:
        output = export_decision_rules(args.memory, args.output)
    except (ValueError, json.JSONDecodeError, OSError) as exc:
        print(f"BOB RULE EXPORT REJECTED: {exc}")
        return 2

    print(f"BOB RULE EXPORT ACCEPTED: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
