"""
COLLIDER regression contract — customer_identity = account_id

Generated by collider.decision_compiler for decision decision-001.
Do not edit by hand; recompile the decision instead. This protects the resolved
canon: any workstream that drifts back to a non-canonical identity fails here.
"""

import json
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from api.handlers import recover as api  # noqa: E402
from ledger import credit_entry as ledger  # noqa: E402

CONCEPT = 'customer_identity'
CANONICAL_VALUE = 'account_id'
DECISION_ID = 'decision-001'
IDENTITY_KWARGS = {'account_id': 'customer_account_id', 'email': 'customer_email'}
SAMPLES = {'account_id': 'acct_42', 'email': 'user@example.com'}


def recover(**identity):
    return api.process_recovery(
        charge_id="ch_contract",
        refund_amount=100,
        notification_contact="user@example.com",
        **identity,
    )


class TestCanonCustomerIdentity(unittest.TestCase):

    def test_decision_memory_records_canon(self):
        memory = json.loads((ROOT / "canon/decision-memory.json").read_text())
        record = next(d for d in memory["decisions"] if d["concept"] == CONCEPT)
        self.assertEqual(record["canonical_value"], CANONICAL_VALUE)
        self.assertEqual(record["decision_state"], "CANONICAL")
        self.assertEqual(record["decision_id"], DECISION_ID)

    def test_spec_carries_canon_marker(self):
        brief = (ROOT / "fixtures/failed-payment/BRIEF.md").read_text()
        self.assertIn(
            f"collider:canon {CONCEPT}={CANONICAL_VALUE} decision={DECISION_ID}",
            brief,
        )

    def test_api_identity_field_is_canonical(self):
        self.assertEqual(api.CUSTOMER_IDENTITY_FIELD, CANONICAL_VALUE)

    def test_ledger_identity_field_is_canonical(self):
        self.assertEqual(ledger.CUSTOMER_IDENTITY_FIELD, CANONICAL_VALUE)

    def test_api_resolves_customer_by_canonical_identity_alone(self):
        kw = IDENTITY_KWARGS[CANONICAL_VALUE]
        result = recover(**{kw: SAMPLES[CANONICAL_VALUE]})
        self.assertEqual(result["customer_field"], CANONICAL_VALUE)
        self.assertEqual(result["customer_value"], SAMPLES[CANONICAL_VALUE])

    def test_api_rejects_non_canonical_identity_alone(self):
        for other, kw in IDENTITY_KWARGS.items():
            if other == CANONICAL_VALUE:
                continue
            with self.assertRaises(ValueError):
                recover(**{kw: SAMPLES[other]})

    def test_api_identity_hands_off_to_ledger_key(self):
        result = recover(**{kw: SAMPLES[v] for v, kw in IDENTITY_KWARGS.items()})
        entry = ledger.post_credit_entry(result["customer_value"], result["refund_amount"])
        self.assertEqual(entry["customer_field"], result["customer_field"])
        self.assertEqual(entry["customer_value"], result["customer_value"])


if __name__ == "__main__":
    unittest.main()
